import { useState, useRef, useEffect } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { motion, AnimatePresence } from "framer-motion";
import {
  BookOpen,
  FileText,
  ArrowLeft,
  Send,
  Sparkles,
  Copy,
  Download,
  RefreshCw,
  Zap,
  CheckCircle,
} from "lucide-react";
import { toast } from "@/hooks/use-toast";

interface Message {
  role: "user" | "assistant";
  content: string;
}

const Notes = () => {
  const [topic, setTopic] = useState("");
  const [noteType, setNoteType] = useState<"revision" | "detailed" | "visual">("revision");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedNotes, setGeneratedNotes] = useState<string | null>(null);

  const noteTypes = [
    { id: "revision", label: "Quick Revision", icon: Zap, description: "Concise bullet points" },
    { id: "detailed", label: "Detailed Notes", icon: FileText, description: "Comprehensive content" },
    { id: "visual", label: "Visual Summary", icon: Sparkles, description: "With diagrams & charts" },
  ];

  const handleGenerate = () => {
    if (!topic.trim()) {
      toast({
        title: "Please enter a topic",
        description: "Tell us what you want to learn about",
        variant: "destructive",
      });
      return;
    }

    setIsGenerating(true);
    
    // Simulate AI generation
    setTimeout(() => {
      const sampleNotes = `# ${topic}

## Key Concepts

### 1. Definition
${topic} is a fundamental concept that involves understanding the core principles and their applications in real-world scenarios.

### 2. Important Points
- **First principle:** The foundation of understanding ${topic} lies in grasping its basic components.
- **Second principle:** Applications extend across multiple domains and use cases.
- **Third principle:** Mastery requires both theoretical knowledge and practical application.

### 3. Formulas & Equations
\`E = mc²\` - This represents the relationship between energy and mass.

### 4. Key Takeaways
1. Start with fundamentals
2. Practice regularly  
3. Apply to real problems
4. Review and reinforce

### 5. Common Mistakes to Avoid
- Skipping foundational concepts
- Not practicing enough examples
- Memorizing without understanding

---
*Generated by StudyAI • ${new Date().toLocaleDateString()}*`;

      setGeneratedNotes(sampleNotes);
      setIsGenerating(false);
      toast({
        title: "Notes generated! 📝",
        description: "Your AI-powered notes are ready",
      });
    }, 2500);
  };

  const handleCopy = () => {
    if (generatedNotes) {
      navigator.clipboard.writeText(generatedNotes);
      toast({ title: "Copied to clipboard!" });
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="icon" asChild>
                <Link to="/dashboard">
                  <ArrowLeft className="w-5 h-5" />
                </Link>
              </Button>
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-br from-primary to-primary-glow rounded-xl flex items-center justify-center shadow-lg shadow-primary/25">
                  <FileText className="w-5 h-5 text-primary-foreground" />
                </div>
                <div>
                  <h1 className="font-display font-bold text-lg">AI Notes Generator</h1>
                  <p className="text-xs text-muted-foreground">Create smart study notes instantly</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {!generatedNotes ? (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-8"
            >
              {/* Topic Input */}
              <Card variant="glass" className="p-8">
                <h2 className="font-display text-xl font-semibold mb-2">What do you want to learn?</h2>
                <p className="text-muted-foreground mb-6">Enter a topic and we'll generate comprehensive notes for you.</p>
                
                <div className="relative">
                  <Input
                    placeholder="e.g., Thermodynamics, Organic Chemistry, Calculus..."
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    className="text-lg h-14 pr-14"
                    onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                  />
                  <Button
                    variant="hero"
                    size="icon"
                    className="absolute right-2 top-1/2 -translate-y-1/2 h-10 w-10"
                    onClick={handleGenerate}
                    disabled={isGenerating}
                  >
                    {isGenerating ? (
                      <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                    ) : (
                      <Sparkles className="w-4 h-4" />
                    )}
                  </Button>
                </div>
              </Card>

              {/* Note Type Selection */}
              <div>
                <h3 className="font-medium mb-4">Choose note style</h3>
                <div className="grid sm:grid-cols-3 gap-4">
                  {noteTypes.map((type) => {
                    const Icon = type.icon;
                    return (
                      <button
                        key={type.id}
                        onClick={() => setNoteType(type.id as typeof noteType)}
                        className={`p-4 rounded-xl border-2 text-left transition-all hover:shadow-lg ${
                          noteType === type.id
                            ? "border-primary bg-primary/10 shadow-md"
                            : "border-border hover:border-primary/50"
                        }`}
                      >
                        <Icon className={`w-6 h-6 mb-2 ${noteType === type.id ? "text-primary" : "text-muted-foreground"}`} />
                        <p className="font-medium">{type.label}</p>
                        <p className="text-xs text-muted-foreground">{type.description}</p>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Recent Topics */}
              <div>
                <h3 className="font-medium mb-4">Recent Topics</h3>
                <div className="flex flex-wrap gap-2">
                  {["Newton's Laws", "Photosynthesis", "Integration", "Chemical Bonding", "World War II"].map((t) => (
                    <button
                      key={t}
                      onClick={() => setTopic(t)}
                      className="px-4 py-2 rounded-full bg-secondary hover:bg-secondary/80 text-sm transition-colors"
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>
            </motion.div>
          ) : (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-4"
            >
              {/* Actions */}
              <div className="flex items-center justify-between">
                <Button variant="ghost" onClick={() => setGeneratedNotes(null)}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Generate New
                </Button>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={handleCopy}>
                    <Copy className="w-4 h-4 mr-2" />
                    Copy
                  </Button>
                  <Button variant="outline" size="sm">
                    <Download className="w-4 h-4 mr-2" />
                    Download
                  </Button>
                  <Button variant="outline" size="sm" onClick={handleGenerate}>
                    <RefreshCw className="w-4 h-4 mr-2" />
                    Regenerate
                  </Button>
                </div>
              </div>

              {/* Notes Content */}
              <Card variant="glass" className="p-8">
                <div className="prose prose-sm max-w-none">
                  <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">
                    {generatedNotes}
                  </div>
                </div>
              </Card>

              {/* Quick Actions */}
              <div className="flex gap-4 pt-4">
                <Button variant="hero" className="flex-1" asChild>
                  <Link to="/doubts">
                    Ask Follow-up Questions
                  </Link>
                </Button>
                <Button variant="glass" className="flex-1" asChild>
                  <Link to="/tests">
                    Take Practice Test
                  </Link>
                </Button>
              </div>
            </motion.div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Notes;
